[package]
name = "rhoughst-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.3"
once_cell = "1.8.0"
[[bin]]
name = "rhoughst-interpreter"
path = "main.rs"
